### ISSUE TITLE
Not compatible with SendinBlue

### ISSUE THREAD

**Issue by GarySwift** [timersys/wordpress-email-templates#12]
Works great except there is compatibility issues with another plugin [SendinBlue Subscribe Form And WP SMTP] (https://wordpress.org/plugins/mailin/).

This is another transactional email service similar to what wpMandrill does.

I can send email with and without SendinBlue but I prefer to use it. Email templates work without SendinBlue but do not work when it is activated.

Any ideas?

**Comment by timersys** [comment]
Hi Gary , please try the following:
Change on includes/class-mailtpl.php 
`$this->loader->add_action( 'phpmailer_init', $this->mailer, 'send_email' );`

To 
`
$this->loader->add_action( 'phpmailer_init', $this->mailer, 'send_email',50 );`

Let me know if it makes any difference.

Regards

**Comment by GarySwift** [comment]
Hi Damian, thank you for responding. Unfortunately it did not work.

I also increased the priority to 100, then 200, then 500 just in case. Tried it each time, still didn't work.

Thanks anyway. I'll be happy to try any more suggestions if you have them.

**Comment by timersys** [comment]
I will need them to add some hooks. Check https://wordpress.org/support/topic/html-emails-support/ and maybe leave your request in there to speed up things :)

**Comment by GarySwift** [comment]
@timersys Thank you very much. That was very cool of you to open that support topic. 

We'll wait and see if they add the hook. I will keep a watch on this and report back if they do add the hook.
