### ISSUE TITLE
Extra white space issue

### ISSUE THREAD

**Issue by DamChtlv** [timersys/wordpress-email-templates#13]
Plugin overall works pretty good,

there is a just a little issue with extra white space in mails on HTML format *(Mails sent from plugins or WCF7 HTML Format).*
**See screens : http://imgur.com/a/xoPLq**

I checked in the code of sent mail and it seems it adds too much "`<br />`" tags at some place it shouldn't like on `"<HTML>, <HEAD>, <TITLE>".`

I'm hoping the plugin keep get updates even if i saw that the last update was 12 months ago...
I don't lose hope :)

Regards,
Damien

**Comment by timersys** [comment]
I can't reproduce. Try deactivating other plguins and changing theme to see if any is affecting or adding those extra br
