### ISSUE TITLE
None of the color choices work

### ISSUE THREAD

**Issue by liftyourgame** [timersys/wordpress-email-templates#14]
I am trying to change the header color but none of the color options work. For example:

Background Color
Choose header background color

but there is no input box or color grid to enable me to choose the color.

![image](https://user-images.githubusercontent.com/292981/33522599-23791b7c-d83c-11e7-9606-6db99df0c03c.png)

**Comment by timersys** [comment]
You have javascript issues most probably. Can't reproduce on clean install
