### ISSUE TITLE
Gravity Forms Notification control

### ISSUE THREAD

**Issue by codepuncher** [timersys/wordpress-email-templates#16]
Hi there,

I have recently had to change parts of a custom template based on what email had been sent from Gravity Forms.
As there is no way to do so out of the box, I’ve had to filter out the email content to replace some HTML using DOMDocument.

Would there be any chance for a feature request to choose email templates per form on Gravity Forms? Like in the form settings? That would make this plugin so damn powerful for users of Gravity Forms.

As a sidenote, with Gravity Forms and this plugin, a lot of extra break tags and empty p tags get added to the top of the email content which I can’t figure out why that’s happening. To workaround this, I have to again use DOMDocument to strip p tags and break tags.

Thanks

**Comment by timersys** [comment]
replied on forums. Not possible with current wordpress email api

**Comment by cliffordp** [comment]
Unsure if relevant but another plugin has this: https://wordpress.org/support/topic/unwanted-space-in-gravity-form-notifications-and-solution/

**Comment by codepuncher** [comment]
This issue has partially been solved by #29
