### ISSUE TITLE
Email address may be an array within array

### ISSUE THREAD

**Issue by nimrod-cohen** [timersys/wordpress-email-templates#17]
Hi Damian,
for some reason wp forums have moderated my response, so I'm writing you here.

You asked me to double check, and what I found is that pluggable.php [line 394] turns the list of recipients to phpmailer from a list of emails (array) to array of arrays (email+empty name)
so if you pass
wp_mail([“1_at_gmail.com”,”2_at_gmail.com”]…)
it turns the email list into:
[
[“1_at_gmail.com”,””],
[“2_at_gmail.com”,””]
]

so your fix still doesn’t work, you need to extract the string from 2 arrays, not just one.

I suggest:
while(is_array($email))
$email = reset($email);

or something similar…

thanks again.

**Comment by timersys** [comment]
Thanks for testing it, please check the dev version again I just commited

**Comment by nimrod-cohen** [comment]
will do now.

**Comment by nimrod-cohen** [comment]
It works :) super happy. thank you!
