### ISSUE TITLE
Plugin wpautop around HTML email elements, causing extra whitespace

### ISSUE THREAD

**Issue by tripflex** [timersys/wordpress-email-templates#18]
First, nice codebase ... very rare to see well documented and structured plugins.  With that said though, it seems that when your plugin runs `wpautop` on the email content, it assumes that the content of the email does not have any HTML elements in it, other than the content of the email ... which may not always be the case.

As an example, in your `header.php` template file, you have opening HTML elements:
https://github.com/timersys/wordpress-email-templates/blob/ff8e1d8e184a5f95bc5ed3b07d9bd4fde3ca971e/admin/templates/partials/header.php#L68-L81

When a plugin other than yours has already formatted and built an email to be sent, there is a chance these have already been added to the email, causing an email like this:

```html
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body>
<p>Hello</p>
<p>Example HTML Content Email:</p>
<p>asdfasdfasdfasdf</p>
</body>
</html>
```

To turn into this:
```html
<p><!DOCTYPE html><br />
<html><br />
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head><br />
<body></p>
<p>Hello</p>
<p>Example HTML Content Email:</p>
<p></body><br />
</html></p>

```

Caused by this:

```php
$this->loader->add_filter( 'mailtpl/email_content', '', 'wpautop' );
```

In my specific situation it's due to Emogrifier returning the full HTML, and yes I could use `emogrifyBodyContent` but that shouldn't be required, as you can't always assume that the email being sent is going to be plain text.

Just like your plugin adds it's own HTML header elements, there's a chance that other plugins or themes will also be doing the same.

I also recommend that you look into using Emogrifier to inline CSS https://github.com/MyIntervals/emogrifier before sending emails as well, to ensure compatibility with all email clients (just a recommendation)

Related to #13

**Comment by gonzalesc** [comment]
Hi @tripflex 
Yes. Sometimes we received questions about it, for example: 
[https://wordpress.org/support/topic/hidden-email-formatting-need-your-help-asap/](https://wordpress.org/support/topic/hidden-email-formatting-need-your-help-asap/)

The plugins should understand that if his principal functions is not the email design, then they are not must modify it, they are not must send a header and footer in his email content.

But we too understand it can happen. We only can recommendate to users to use the hooks of these plugins  to remove headers anda footers.

On the other hand, about of Emogrifier, we will use it in future versions.

Regards
