### ISSUE TITLE
Generic method for other plugins that override wp_mail

### ISSUE THREAD

**Issue by crobbinsdg** [timersys/wordpress-email-templates#20]
Great plugin and code btw.

There are plenty of plugins out there that override the wp_mail function to send mail using various services.  Specifically I an looking at use cases for [WP SES](https://wordpress.org/plugins/wp-ses/)  and https://github.com/humanmade/aws-ses-wp-mail.  I was thinking it would be great if you had a generic method similar to the Postman compatibility method `send_email_postman`  but without the class exists check.

Currently I'm making things work by just adding a dummy class for Postman.

Maybe something like this in `class-mailtpl-mailer.php`.  

```
public function send_email_wp_mail( $args ) {
	do_action( 'mailtpl/send_email_wp_mail', $args, $this );
	$temp_message       =  $this->add_template( apply_filters( 'mailtpl/email_content', $args['message'] ) );
	$user_email = isset( $args['to'] ) ? $args['to'] : $args;
	$args['message']    =  $this->replace_placeholders( $temp_message, $user_email );
	return $args;
}
```
Then it would be up to the developer to add a hook like:
```
$Mailtpl = Mailtpl::instance();
add_filter( 'wp_mail', array($Mailtpl->mailer, 'send_email_wp_mail') );
```

**Comment by gonzalesc** [comment]
Hi,
This is generic:
`$this->loader->add_action( 'phpmailer_init', $this->mailer, 'send_email', 50 );`

I still do not understand what are your purpose.
Regards

**Comment by crobbinsdg** [comment]
@gonzalesc Correct that is the generic hook if your are sending mail using the PHPMailer class.  I am asking about a generic method for plugins that overwrite the `wp_mail` function.  Typically they are sending mail out using a different service (examples: AWS SES, Mailgun, or other transactional mail services).

**Comment by crobbinsdg** [comment]
The Postman compatibility method `send_email_postman` is a great example of a plugin that overwrites the `wp_mail` function and uses its own class to send mail (instead of PHPMailer).  However that method requires that the `Postman` class exist.

Basically I am asking for a method that is generic for all the other plugins that don't use `PHPMailer` (and instead overwrite `wp_mail`).  I understand that having that new method active by default would break compatibility with other plugins that use `PHPMailer`.  So it would be up to the developer to add the appropriate hook for that method.

**Comment by gonzalesc** [comment]
Hi.
This plugin has some changes: we verify compatibility with others plugins, delete us methods we not use and we unify generic methods.

Actually, all those changes are in revision. This new code is in wpmail branch if you want to see.

Regards

**Comment by crobbinsdg** [comment]
Right on.  New code looks great.  Thanks!
