### ISSUE TITLE
Customizer mail-template preview not working if woocommerce is active

### ISSUE THREAD

**Issue by erichk4** [timersys/wordpress-email-templates#22]
hi,

the hook "template_include" -> "capture_customizer_page" need's a higher priority value

**includes\class-mailtpl.php #190:**

`$this->loader->add_action( 'template_include', $this->customizer, 'capture_customizer_page', 999 );`

after raising the priority value to e.g. 999 the preview is working as excepted...

**Comment by gonzalesc** [comment]
Hi.
I have Woocommerce active and I can see good the preview. Maybe other plugin too set this hook.

**Comment by erichk4** [comment]
got it:
if a theme defines explicit woocommerce support via `add_theme_support( 'woocommerce' );`
then woocommerce itself uses this hook to load the template (in "woocommerce\includes\class-wc-template-loader.php") so we need a higher priority  to override it

**Comment by erichk4** [comment]
fixed #23
