### ISSUE TITLE
Include plain text

### ISSUE THREAD

**Issue by serge22** [timersys/wordpress-email-templates#24]
Is it possible to include email in plain text as well? Spam filters does not like email with HTML version only. It would be cool if email contains both HTML and text versions

**Comment by gonzalesc** [comment]
Hi.
Do you is talking about of Multi-Part MIME ?

Regards

**Comment by serge22** [comment]
Hi! Yes, I'm talking about multipart mime. Is it difficult to implement?

**Comment by timersys** [comment]
Hi Serge22,
yes at the moment it's complicate, I'm afraid we opted for a more generic solution.
