### ISSUE TITLE
Full width template is not really full width

### ISSUE THREAD

**Issue by horecny** [timersys/wordpress-email-templates#28]
Hi,

if you try to set up full width template and put content which is tiny - like 3 words in row, email size is really not 100% width - fullwidth but looks like email with boxed template.

Header logo we have custom with max-width 200px.

I see in your code, that you define in header.php (template)
`max-width: " . ( $settings['template'] == 'boxed' ? $settings['body_size'] . 'px' : '100%' ) . ";";`

Should be just width: no?

**Comment by timersys** [comment]
Fixed already, not launched yet
