### ISSUE TITLE
display:inline-block stripped from template

### ISSUE THREAD

**Issue by carletto0282** [timersys/wordpress-email-templates#4]
Hi guys,

I'm trying to set up a table like template using your plugin.
Actually it's working like a charm except for one thing: it strip every display css rule I'm trying to add inline.

Is it possible to change this behaviour?
Thanks
Best regards
Carlo

**Comment by timersys** [comment]
how are you creating that template?

**Comment by carletto0282** [comment]
Just pasting the html in the customizer field of email template

**Comment by timersys** [comment]
In order to use a new template you need to create new files and use filters to load your template instead of plugin's one.
Check mailtpl/customizer_template

**Comment by carletto0282** [comment]
I'll do.
Thank you very much
