### ISSUE TITLE
Emails not sending due to "Message body empty"

### ISSUE THREAD

**Issue by codepuncher** [timersys/wordpress-email-templates#40]
This has many different scenarios that trigger the bug.
However, the one that I have tested and can confirm with is by using Gravity Forms.

To replicate:
1. Create a form with some fields
2. Create more than 1 notification that will send
3. Submit your form

Only 1 notification will send. The remaining will fail to send and say "Message body empty".
![Screenshot 2021-04-28 at 10 58 28](https://user-images.githubusercontent.com/8135396/116385414-ad937f80-a810-11eb-8d06-fab7bc178dad.png)

It is caused by #29

**Comment by codepuncher** [comment]
On further inspection, it appears that the PR introduces a breaking change.
Any [custom templates](https://timersys.com/customize-wordpress-email-templates-plugin/) made that use `include_once` will need to be refactored to use `include` instead.

**Comment by timersys** [comment]
The problem is that most users don't use custom templates. They just use other plugins and we cannot refactor all of them. I haven't got time yet to look to a solution but I was thinking to simply revert #29

**Comment by codepuncher** [comment]
Rather than revert a very useful feature, why not [pin this thread](https://wordpress.org/support/topic/bug-fix-for-message-body-empty/) to your support forum for users to see?
Or maybe introduce a WP notification which can be dismissed regarding this?
I wouldn't imagine that "custom templates" is a hugely popular feature so (as you've mentioned), so, reverting doesn't seem to be worthwhile IMO.

It would be for those users that are more technical to implement custom templates, so they would be very likely to see this in the support forum.

**Comment by codepuncher** [comment]
Closing as there is nothing to "fix" in the plugin source code.
