### ISSUE TITLE
add option to choose box width

### ISSUE THREAD

**Issue by carletto0282** [timersys/wordpress-email-templates#5]
Hi,
I'd like to ask you if it's possible to add an option to choose the box width.
Now it's set to 680px
I see many newsletter services set it to 600px.
I'm going to edit plugin code to set it that way but it would be awesome if it is possible to choose box width right from the customizer.

Thanks
Carlo

**Comment by timersys** [comment]
Added in eaf69b3

**Comment by carletto0282** [comment]
Thank you!
