### ISSUE TITLE
alt text for logo as attachment title

### ISSUE THREAD

**Issue by carletto0282** [timersys/wordpress-email-templates#6]
Hi,

I'd like to ask you if it's possible to change the alt text for the image logo to something different from "logo".

The best thing would be a custom field in the customizer. But it would be good even if it take the attachment title set trough the main wordpress media manager.

Thanks
Best regards
Carlo

**Comment by timersys** [comment]
I added bloginfo('description') and a filter to let users change it, but I don't want to add more option to customizer to keep it simple.
done in b2ee640

**Comment by carletto0282** [comment]
Great! Thanks
