### ISSUE TITLE
WooCommerce email headers overwritten

### ISSUE THREAD

**Issue by decarvalhoaa** [timersys/wordpress-email-templates#8]
hello,

I believe the plugin replaces WooCommerce email headers and footers with the plugin own header and footer with this code here https://github.com/timersys/wordpress-email-templates/blob/master/admin/class-mailtpl-admin.php#L206-L207.

However you can setup custom headers for each WooCommerce email. Is there a way instead to suppress the plugin header and use WooCommerce's? Or alternative if all possible, don't apply the plugin template to WooCommerce emails?

Ideally, you could add a menu in the Customizer, to exclude some plugins that generate Emails (with a small switch) like WooCommerce or other future plugin that may create conflicts with this plugin.

**Comment by Mark-Joy** [comment]
I am having the exact same issue. It would be nice if there is an option to exclude WooCommerce email from being affected.

**Comment by timersys** [comment]
The problem is that WordPress email API it's very limited and there is no way to know where the emails are coming. 
Can't you add a header inside the content of each email? Is either that or disable the plugin and use just woocommerce ones
