### ISSUE TITLE
How to add/change custom CSS 

### ISSUE THREAD

**Issue by decarvalhoaa** [timersys/wordpress-email-templates#9]
Hello,

I wanted too change some css in the template but didn't find a way without changing the plugin files at
wordpress-email-templates/admin/templates/partials/header.php
wordpress-email-templates/admin/templates/partials/footer.php

Things like styling links could be easily added to the Customizer, but I think that for "power users" you could consider applying filters in the header.php and footer.php template files when you define the css variables like for example

```
$wrapper = apply_filter( 'filter-name', "
    background-color:".$settings['body_bg'].";
    width:100%;
    -webkit-text-size-adjust:none !important;
    margin:0;
    padding: 70px 0 70px 0;
");

```

or for even higher flexibility, lookup the active theme folder for templates that could overwrite the files in wordpress-email-templates/admin/templates/partials/ instead of include the files directly in wordpress-email-templates/admin/templates/default.php.

This enhancement would be much appreciated. Thank you.

**Comment by micahjon** [comment]
+1

**Comment by timersys** [comment]
Do you have a custom css box in the template section already
